export const INIT_GOALS=[
  // ═══ Mål 1: Teknologi og ehelse ═══
  {id:"G-01",title:"Vi er i front med teknologi og ehelse for en fremtidsrettet helsetjeneste",type:"Hovedmål",parent:null,metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-02",title:"Vår metodikk og virksomhetsforståelse sikrer nytteverdi for helsetjenesten og pasienten",type:"Delmål",parent:"G-01",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-03",title:"Vi legger til rette for utvikling som bidrar til automatisering og selvbetjening i helsetjenesten",type:"Delmål",parent:"G-01",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-04",title:"Vi bidrar til effektive og helhetlige prosesser gjennom riktig bruk av teknologi",type:"Delmål",parent:"G-01",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-05",title:"Vi bidrar til å nå FNs bærekraftsmål",type:"Delmål",parent:"G-01",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  // ═══ Mål 2: Samarbeid ═══
  {id:"G-06",title:"Gjennom samarbeid skaper vi den beste helsetjenesten",type:"Hovedmål",parent:null,metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-07",title:"Vi bygger tverrfaglige og klinikknære team",type:"Delmål",parent:"G-06",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-08",title:"Vi samarbeider med Helseplattformen og andre leverandører for å sikre nytteverdi for helsetjenesten og pasienten",type:"Delmål",parent:"G-06",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-09",title:"Vi leverer tjenester og bidrar til samarbeid på tvers av helseregioner",type:"Delmål",parent:"G-06",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-10",title:"Vi er en foretrukken samarbeidspartner for forskning, utdanning og innovasjon innen teknologi og ehelse",type:"Delmål",parent:"G-06",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  // ═══ Mål 3: Sikkerhet og pålitelighet ═══
  {id:"G-11",title:"Helsetjenesten skal alltid ha høy tillit til sikkerhet og pålitelighet i våre tjenester",type:"Hovedmål",parent:null,metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-12",title:"Vi er pådriver for en helhetlig risikostyring",type:"Delmål",parent:"G-11",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-13",title:"Vi videreutvikler kontinuerlig en sikker og robust infrastruktur",type:"Delmål",parent:"G-11",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-14",title:"Vi bidrar til god sikkerhetskultur i HMN",type:"Delmål",parent:"G-11",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-15",title:"Vi tar en aktiv rolle i den helhetlige beredskapen",type:"Delmål",parent:"G-11",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  // ═══ Mål 4: Attraktiv arbeidsplass ═══
  {id:"G-16",title:"Vi er regionens mest attraktive arbeidsplass innen teknologi og e-helse",type:"Hovedmål",parent:null,metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-17",title:"Vi rekrutterer, utvikler og beholder kompetente medarbeidere",type:"Delmål",parent:"G-16",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-18",title:"Vi bygger sterke fagmiljø",type:"Delmål",parent:"G-16",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-19",title:"Vi løser meningsfulle og inspirerende oppgaver",type:"Delmål",parent:"G-16",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-20",title:"Vi er stolte av vårt gode arbeidsmiljø",type:"Delmål",parent:"G-16",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  // ═══ Mål 5: Foretrukken leverandør ═══
  {id:"G-21",title:"Vi er regionens foretrukne leverandør av fellestjenester",type:"Hovedmål",parent:null,metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-22",title:"Vi leverer kostnadseffektive fellestjenester med høy nytteverdi",type:"Delmål",parent:"G-21",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-23",title:"Vi ivaretar regional forvaltning av Helseplattformen",type:"Delmål",parent:"G-21",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
  {id:"G-24",title:"Som tjenesteintegrator tar vi et helhetsansvar for regionens IKT-tjenester",type:"Delmål",parent:"G-21",metric:"",baseline:"",target:"",current:"",deadline:"",kpiStatus:"on-track",kpiHistory:[]},
];

export const INIT_TASKS=[
  // ═══ T-001: Automatisere fakturautsending (RPA) — FERDIG ═══
  {id:"T-001",title:"Automatisere fakturautsending",desc:"Robotisere manuell fakturaprosess i økonomiavd.",tracks:["rpa"],size:0,status:"done",sprintId:"S-27",submitterName:"Kari Haugen",submitterDept:"Økonomiavd.",processOwner:"Økonomisjef Trond Lie",date:"2026-01-20",reviewed:true,priority:"high",goals:["G-03","G-04"],eqsRef:"EQS-2024-0142 Fakturahåndtering",personalData:"no",parentId:null,
    enterprise:"hemit",solutionCategory:"rpa",serviceNowRef:"REQ-2026-0041",pilotUnit:"Økonomiavd. seksjon regnskap",
    manualTask:"yes",taskPerformer:"Regnskapskonsulenter",frequency:"Daglig",volumePerTime:"80 fakturaer",annualTimeSaving:"1600",involvedSystems:"SAP, EHF, Basware",
    needSummary:"Automatisere manuell fakturakontroll og kontering",background:"Økonomiavd. bruker 40t/uke på manuell fakturabehandling i 3 systemer",
    qualitativeBenefits:"Redusert feilrate, raskere behandlingstid, bedre sporbarhet",quantitativeBenefits:"70% reduksjon i manuell tid, ca 1600 timer/år spart",
    regulatory:3,security:2,costSaving:9,dataQuality:7,simplicity:8,patientBenefit:1,employeeSat:7,
    regulatoryReason:"Marginalt – fakturahåndtering er ikke direkte regulert",securityReason:"Lav risiko – ingen sensitive data",costSavingReason:"Svært høy – 1600 t/år frigjort",dataQualityReason:"Færre manuelle feil i kontering",simplicityReason:"Fjerner repetitivt manuelt arbeid",patientBenefitReason:"Ingen direkte pasienteffekt",employeeSatReason:"Fjerner monotont arbeid fra ansatte",
    expectedBenefit:"Redusere manuell fakturabehandling med 70%",benefitCategory:"time",benefitClassification:"kvantitativ",benefitUnit:"timer",benefitMetric:"Manuell tid per uke",benefitBaseline:"40",benefitTarget:"12",benefitActual:"14",benefitOwner:"Trond Lie",estimatedCost:"150000",estimatedAnnualSaving:"320000",
    benefitPlan:[{date:"2026-06-01",responsible:"Trond Lie",method:"Tidsmåling",milestone:"3-mndrs måling",measured:true,value:"14"},{date:"2026-09-01",responsible:"Trond Lie",method:"Tidsmåling",milestone:"6-mndrs måling",measured:false,value:""}],
    pirRealization:4,pirSatisfaction:4,pirProcess:5,pirTechnical:4,pirStakeholderScore:4,pirOutcome:"realized",pirLessonCategories:[{category:"process",text:"Bot feiler ved ugyldige org.nr – trenger feilhåndtering"},{category:"technical",text:"UiPath Cloud stabil, lokal orkestrator hadde timeout-problemer"}],pirActionItems:[{action:"Utvide bot til å håndtere kreditnotaer",responsible:"Ida Berg",deadline:"2026-04-01",done:false}],
    comments:[{author:"Utviklingsforum",text:"Høy ROI – prioriteres i S-27.",time:"2026-01-22 09:15"},{author:"Leveranseteam",text:"Bot levert og i produksjon.",time:"2026-02-14 15:00"}],
    history:[{who:"System",what:"Opprettet",time:"2026-01-20 08:00"},{who:"Utviklingsforum",what:"Status → Klar for sprint",time:"2026-01-22 09:15"},{who:"System",what:"status → \"in-progress\"",time:"2026-02-03 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-14 16:00"}],attachments:[]},
  {id:"T-001-A",title:"Kartlegge fakturaprosess (AS-IS)",desc:"Dokumentere nåværende manuell flyt.",tracks:["rpa"],size:3,status:"done",sprintId:"S-27",submitterName:"Kari Haugen",submitterDept:"Økonomiavd.",processOwner:"Økonomisjef Trond Lie",date:"2026-01-21",reviewed:true,priority:"high",goals:["G-03"],parentId:"T-001",personalData:"no",actualHours:12,assignee:"m6",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-21 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-07 16:00"}],attachments:[]},
  {id:"T-001-B",title:"Utvikle RPA-bot for faktura",desc:"Bygge UiPath-bot for automatisk fakturabehandling.",tracks:["rpa"],size:5,status:"done",sprintId:"S-27",submitterName:"Kari Haugen",submitterDept:"Økonomiavd.",processOwner:"Økonomisjef Trond Lie",date:"2026-01-22",reviewed:true,priority:"high",goals:["G-03"],parentId:"T-001",personalData:"no",actualHours:22,assignee:"m6",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-22 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-12 16:00"}],attachments:[]},
  {id:"T-001-C",title:"Test og pilot faktura-bot",desc:"UAT med økonomiavdelingen, pilotperiode 2 uker.",tracks:["rpa"],size:3,status:"done",sprintId:"S-27",submitterName:"Kari Haugen",submitterDept:"Økonomiavd.",processOwner:"Økonomisjef Trond Lie",date:"2026-01-22",reviewed:true,priority:"high",goals:["G-03"],parentId:"T-001",personalData:"no",actualHours:8,assignee:"m5",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-22 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-14 14:00"}],attachments:[]},

  // ═══ T-002: Pasientportal med timebooking (Systemutvikling) — PÅGÅR ═══
  {id:"T-002",title:"Pasientportal med timebooking",desc:"Selvbetjeningsløsning for pasienter med timebestilling, prøvesvar og meldinger.",tracks:["sysdev"],size:0,status:"in-progress",sprintId:"S-28",submitterName:"Dr. Hanne Bakke",submitterDept:"Poliklinikk",processOwner:"Avd.leder poliklinikk",date:"2026-01-10",reviewed:true,priority:"high",goals:["G-01","G-03","G-02"],parentId:null,
    enterprise:"stolav",solutionCategory:"sysdev",serviceNowRef:"REQ-2026-0028",pilotUnit:"Medisinsk poliklinikk",
    manualTask:"yes",taskPerformer:"Helsesekretærer",frequency:"Daglig",volumePerTime:"120 henvendelser",annualTimeSaving:"2400",involvedSystems:"DIPS Arena, Helseplattformen, HelseNorge",
    needSummary:"Pasienter skal kunne bestille, endre og avbestille timer digitalt",background:"70% av timebestillinger skjer per telefon, dette belaster sekretærer og gir ventetid for pasienter",
    qualitativeBenefits:"Bedre pasientopplevelse, redusert ventetid, økt tilgjengelighet",quantitativeBenefits:"2400 timer/år spart for helsesekretærer, 40% færre telefoner",
    personalData:"yes",eqsRef:"EQS-2025-0033 Pasientkommunikasjon",
    regulatory:6,security:8,costSaving:7,dataQuality:5,simplicity:7,patientBenefit:9,employeeSat:6,
    regulatoryReason:"Pasientrettigheter krever tilgjengelig informasjon",securityReason:"Behandler personopplysninger – krever DPIA og sikker autentisering",costSavingReason:"2400 t/år spart",dataQualityReason:"Strukturert datainnsamling fra pasienter",simplicityReason:"Erstatter telefon med digital selvbetjening",patientBenefitReason:"Stor forbedring – pasienter styrer egne timer",employeeSatReason:"Færre telefonhenvendelser for sekretærer",
    expectedBenefit:"Redusere telefonbaserte timebestillinger med 60%",benefitCategory:"time",benefitClassification:"kvantitativ",benefitUnit:"timer",benefitMetric:"Telefonhenvendelser per dag",benefitBaseline:"120",benefitTarget:"48",benefitActual:"",benefitOwner:"Dr. Hanne Bakke",estimatedCost:"450000",estimatedAnnualSaving:"520000",
    benefitPlan:[{date:"2026-06-01",responsible:"Dr. Hanne Bakke",method:"Telefonlogg",milestone:"3-mndrs pilot",measured:false,value:""},{date:"2026-09-01",responsible:"Dr. Hanne Bakke",method:"Telefonlogg",milestone:"6-mndrs evaluering",measured:false,value:""}],
    comments:[{author:"Utviklingsforum",text:"Høy pasientnytteverdi – prioritert.",time:"2026-01-15 10:00"},{author:"CISO",text:"DPIA gjennomført – godkjent med vilkår om BankID-autentisering.",time:"2026-01-20 14:30"}],
    history:[{who:"System",what:"Opprettet",time:"2026-01-10 08:00"},{who:"Utviklingsforum",what:"status → \"assessed\"",time:"2026-01-15 10:00"},{who:"System",what:"status → \"ready\"",time:"2026-01-28 09:00"},{who:"System",what:"status → \"in-progress\"",time:"2026-02-17 08:00"}],attachments:[]},
  {id:"T-002-A",title:"Kravspesifikasjon pasientportal",desc:"Funksjonelle og ikke-funksjonelle krav.",tracks:["sysdev"],size:3,status:"done",sprintId:"S-27",submitterName:"Dr. Hanne Bakke",submitterDept:"Poliklinikk",processOwner:"Avd.leder poliklinikk",date:"2026-01-16",reviewed:true,priority:"high",goals:["G-03"],parentId:"T-002",actualHours:16,assignee:"m1",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-16 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-07 16:00"}],attachments:[]},
  {id:"T-002-B",title:"Design UI/UX pasientportal",desc:"Wireframes, prototyp og brukertest med pasienter.",tracks:["sysdev"],size:5,status:"done",sprintId:"S-27",submitterName:"Dr. Hanne Bakke",submitterDept:"Poliklinikk",processOwner:"Avd.leder poliklinikk",date:"2026-01-17",reviewed:true,priority:"high",goals:["G-03"],parentId:"T-002",actualHours:20,assignee:"m2",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-17 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-14 15:00"}],attachments:[]},
  {id:"T-002-C",title:"Backend API for timebooking",desc:"REST-API med HelseNorge og DIPS-integrasjon.",tracks:["sysdev","integration"],size:8,status:"in-progress",sprintId:"S-28",submitterName:"Dr. Hanne Bakke",submitterDept:"Poliklinikk",processOwner:"Avd.leder poliklinikk",date:"2026-01-18",reviewed:true,priority:"high",goals:["G-03"],parentId:"T-002",actualHours:14,assignee:"m1",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-18 08:00"},{who:"System",what:"status → \"in-progress\"",time:"2026-02-17 08:30"}],attachments:[]},
  {id:"T-002-D",title:"Frontend pasientportal",desc:"React-app med responsivt design og BankID-innlogging.",tracks:["sysdev"],size:8,status:"ready",sprintId:"S-28",submitterName:"Dr. Hanne Bakke",submitterDept:"Poliklinikk",processOwner:"Avd.leder poliklinikk",date:"2026-01-18",reviewed:true,priority:"high",goals:["G-03"],parentId:"T-002",assignee:"m2",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-18 08:00"}],attachments:[]},
  {id:"T-002-E",title:"Sikkerhet og penetrasjonstest",desc:"Sikkerhetsgjennomgang og pentest av portalen.",tracks:["sysdev"],size:3,status:"ready",sprintId:"S-29",submitterName:"Dr. Hanne Bakke",submitterDept:"Poliklinikk",processOwner:"Avd.leder poliklinikk",date:"2026-01-18",reviewed:true,priority:"high",goals:["G-12"],parentId:"T-002",assignee:"m5",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-18 08:00"}],attachments:[]},

  // ═══ T-003: Oppgradere CRM-integrasjon (Integrasjon) — FERDIG ═══
  {id:"T-003",title:"Oppgradere CRM-integrasjon",desc:"Migrere fra SOAP til ny REST-API versjon for kundehåndtering.",tracks:["integration"],size:0,status:"done",sprintId:"S-27",submitterName:"Erik Holm",submitterDept:"IT-drift",processOwner:"CRM-forvalter",date:"2026-01-18",parentId:null,reviewed:true,priority:"medium",goals:["G-01","G-13"],
    enterprise:"hemit",solutionCategory:"integration",serviceNowRef:"CHG-2026-0015",
    manualTask:"no",taskPerformer:"",frequency:"",volumePerTime:"",annualTimeSaving:"200",involvedSystems:"Dynamics 365, Mulesoft, DIPS",
    needSummary:"Oppgradere CRM-integrasjon fra SOAP til REST",background:"Nåværende SOAP-grensesnitt er ustabilt og gir driftsproblemer 2-3 ganger/mnd",
    regulatory:2,security:5,costSaving:5,dataQuality:7,simplicity:6,patientBenefit:3,employeeSat:5,
    regulatoryReason:"Lav – CRM er ikke direkte regulert",securityReason:"Moderne API sikrer bedre tokenbasert autentisering",costSavingReason:"Redusert driftskostnad og feilretting",dataQualityReason:"REST gir bedre datavalidering og feilhåndtering",simplicityReason:"Enklere vedlikehold av ny integrasjon",patientBenefitReason:"Indirekte – mer stabil henvendelseshåndtering",employeeSatReason:"Færre driftsproblemer å håndtere",
    expectedBenefit:"Stabil og vedlikeholdbar integrasjon",benefitCategory:"quality",benefitClassification:"kvalitativ",benefitOwner:"Erik Holm",estimatedCost:"80000",estimatedAnnualSaving:"95000",actualHours:32,assignee:"m1",benefitBaseline:"120",benefitTarget:"60",benefitActual:"55",
    comments:[{author:"Leveranseteam",text:"REST-migrering fullført.",time:"2026-02-13 11:00"}],
    history:[{who:"System",what:"Opprettet",time:"2026-01-18 08:00"},{who:"System",what:"status → \"in-progress\"",time:"2026-02-03 09:00"},{who:"System",what:"status → \"done\"",time:"2026-02-13 16:00"}],attachments:[]},
  {id:"T-003-A",title:"Kartlegge integrasjonspunkter",desc:"Dokumentere alle SOAP-endepunkter og datamappinger.",tracks:["integration"],size:3,status:"done",sprintId:"S-27",submitterName:"Erik Holm",submitterDept:"IT-drift",processOwner:"CRM-forvalter",date:"2026-01-19",reviewed:true,priority:"medium",goals:["G-13"],parentId:"T-003",actualHours:10,assignee:"m1",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-19 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-05 16:00"}],attachments:[]},
  {id:"T-003-B",title:"Utvikle REST-integrasjon",desc:"Implementere ny REST-klient med Mulesoft.",tracks:["integration"],size:5,status:"done",sprintId:"S-27",submitterName:"Erik Holm",submitterDept:"IT-drift",processOwner:"CRM-forvalter",date:"2026-01-19",reviewed:true,priority:"medium",goals:["G-13"],parentId:"T-003",actualHours:16,assignee:"m1",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-19 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-11 16:00"}],attachments:[]},
  {id:"T-003-C",title:"Test og verifisering CRM",desc:"Ende-til-ende testing og overgang til produksjon.",tracks:["integration"],size:3,status:"done",sprintId:"S-27",submitterName:"Erik Holm",submitterDept:"IT-drift",processOwner:"CRM-forvalter",date:"2026-01-19",reviewed:true,priority:"medium",goals:["G-13"],parentId:"T-003",actualHours:6,assignee:"m5",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-19 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-13 15:00"}],attachments:[]},

  // ═══ T-004: Automatisk medikamentdoseringssjekk (Sysdev) — PÅGÅR ═══
  {id:"T-004",title:"Automatisk medikamentdoseringssjekk",desc:"Beslutningsstøtte som varsler ved potensielle doseringsfeil basert på pasientdata.",tracks:["sysdev","integration"],size:0,status:"in-progress",sprintId:"S-28",submitterName:"Dr. Stein Iversen",submitterDept:"Farmasi",processOwner:"Sjefsfarmasøyt",date:"2026-01-25",parentId:null,reviewed:true,priority:"high",goals:["G-11","G-12"],
    enterprise:"stolav",solutionCategory:"sysdev",serviceNowRef:"REQ-2026-0052",pilotUnit:"Intensivavd.",personalData:"yes",
    eqsRef:"EQS-2025-0055 Legemiddelhåndtering",
    manualTask:"yes",taskPerformer:"Farmasøyter og sykepleiere",frequency:"Kontinuerlig",volumePerTime:"300 doseringer/dag",annualTimeSaving:"800",involvedSystems:"Helseplattformen, FEST, Farmalogg",
    needSummary:"Automatisk sjekk av medikamentdosering mot pasientens vekt, nyrefunksjon og interaksjoner",background:"3 alvorlige doseringsfeil siste halvår, manuell sjekk er tidkrevende og feilutsatt",
    qualitativeBenefits:"Økt pasientsikkerhet, redusert risiko for medikamentfeil",quantitativeBenefits:"Estimert 90% reduksjon i doseringsfeil, 800 timer/år spart",
    regulatory:9,security:7,costSaving:5,dataQuality:8,simplicity:6,patientBenefit:10,employeeSat:7,
    regulatoryReason:"Lovkrav om forsvarlig legemiddelhåndtering",securityReason:"Behandler sensitiv helseinformasjon",costSavingReason:"Tidsbesparelse på manuelle kontroller",dataQualityReason:"Strukturert doseringsinformasjon med automatisk validering",simplicityReason:"Automatiserer kompleks manuell prosess",patientBenefitReason:"Direkte livreddende – forhindrer alvorlige doseringsfeil",employeeSatReason:"Tryggere arbeidshverdag for helsepersonell",
    expectedBenefit:"Redusere medikamentfeil med 90%",benefitCategory:"quality",benefitClassification:"kvantitativ",benefitUnit:"antall",benefitMetric:"Doseringsfeil per måned",benefitBaseline:"6",benefitTarget:"1",benefitActual:"",benefitOwner:"Dr. Stein Iversen",estimatedCost:"380000",estimatedAnnualSaving:"250000",
    blockedBy:[],
    comments:[{author:"Utviklingsforum",text:"Kritisk pasientsikkerhet – topp prioritet.",time:"2026-01-28 09:00"},{author:"CISO",text:"DPIA godkjent, krever kryptering av alle pasientdata.",time:"2026-02-01 11:00"}],
    history:[{who:"System",what:"Opprettet",time:"2026-01-25 08:00"},{who:"Utviklingsforum",what:"status → \"assessed\"",time:"2026-01-28 09:00"},{who:"System",what:"status → \"ready\"",time:"2026-02-10 10:00"},{who:"System",what:"status → \"in-progress\"",time:"2026-02-17 08:00"}],attachments:[]},
  {id:"T-004-A",title:"Kravspesifikasjon doseringssjekk",desc:"Kliniske krav og regler for doseringskontroll.",tracks:["sysdev"],size:3,status:"done",sprintId:"S-27",submitterName:"Dr. Stein Iversen",submitterDept:"Farmasi",processOwner:"Sjefsfarmasøyt",date:"2026-01-26",reviewed:true,priority:"high",goals:["G-11"],parentId:"T-004",actualHours:14,assignee:"m1",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-26 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-10 16:00"}],attachments:[]},
  {id:"T-004-B",title:"FEST-integrasjon for interaksjonsdata",desc:"Hente legemiddeldata fra FEST-registeret via API.",tracks:["integration"],size:5,status:"in-progress",sprintId:"S-28",submitterName:"Dr. Stein Iversen",submitterDept:"Farmasi",processOwner:"Sjefsfarmasøyt",date:"2026-01-26",reviewed:true,priority:"high",goals:["G-11"],parentId:"T-004",actualHours:8,assignee:"m3",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-26 08:00"},{who:"System",what:"status → \"in-progress\"",time:"2026-02-17 09:00"}],attachments:[]},
  {id:"T-004-C",title:"Utvikle doseringsalgoritme",desc:"Regelmotor for dosekontroll basert på vekt, alder, nyrefunksjon.",tracks:["sysdev"],size:8,status:"ready",sprintId:"S-28",submitterName:"Dr. Stein Iversen",submitterDept:"Farmasi",processOwner:"Sjefsfarmasøyt",date:"2026-01-26",reviewed:true,priority:"high",goals:["G-11"],parentId:"T-004",assignee:"m1",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-26 08:00"}],attachments:[]},
  {id:"T-004-D",title:"Klinisk validering og test",desc:"Test med farmasøyter og klinisk personell.",tracks:["sysdev"],size:3,status:"ready",sprintId:"S-29",submitterName:"Dr. Stein Iversen",submitterDept:"Farmasi",processOwner:"Sjefsfarmasøyt",date:"2026-01-26",reviewed:true,priority:"high",goals:["G-11"],parentId:"T-004",assignee:"m5",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-26 08:00"}],attachments:[]},

  // ═══ T-005: SSO-pålogging alle systemer (Sysdev) — KLAR ═══
  {id:"T-005",title:"SSO-pålogging alle systemer",desc:"Azure AD SSO med MFA for alle interne systemer.",tracks:["sysdev"],size:0,status:"ready",sprintId:"S-28",submitterName:"Jonas Ribe",submitterDept:"Sikkerhet",processOwner:"CISO",date:"2026-01-25",parentId:null,reviewed:true,priority:"medium",goals:["G-13","G-14"],eqsRef:"EQS-2023-0088 Tilgangsstyring",personalData:"yes",
    enterprise:"hemit",solutionCategory:"sysdev",
    manualTask:"yes",taskPerformer:"IT brukerstøtte",frequency:"Daglig",volumePerTime:"50 påloggingshenvendelser",annualTimeSaving:"400",involvedSystems:"Azure AD, Citrix, DIPS, HMN nett",
    needSummary:"Enkel pålogging med SSO og MFA for alle interne systemer",background:"Ansatte logger seg inn i 5-8 systemer daglig med ulike passord, genererer mange brukerstøttehenvendelser",
    regulatory:5,security:9,costSaving:4,dataQuality:3,simplicity:8,patientBenefit:2,employeeSat:9,
    regulatoryReason:"MFA-krav fra NSM og Helsedirektoratet",securityReason:"Eliminerer passordgjenbruk og svake passord",costSavingReason:"Færre brukerstøttehenvendelser",dataQualityReason:"Bedre tilgangsstyring og logging",simplicityReason:"Én pålogging i stedet for 5-8",patientBenefitReason:"Indirekte – raskere tilgang til kliniske systemer",employeeSatReason:"Stor forbedring i daglig arbeid",
    expectedBenefit:"Én pålogging for alle systemer",benefitCategory:"satisfaction",benefitClassification:"kvalitativ",benefitOwner:"Jonas Ribe",estimatedCost:"60000",estimatedAnnualSaving:"85000",assignee:"m5",actualHours:4,
    comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-25 08:00"},{who:"System",what:"status → \"ready\"",time:"2026-02-01 10:00"}],attachments:[]},
  {id:"T-005-A",title:"Kartlegge SSO-kompatibilitet",desc:"Sjekke hvilke systemer som støtter SAML/OIDC.",tracks:["sysdev"],size:2,status:"done",sprintId:"S-27",submitterName:"Jonas Ribe",submitterDept:"Sikkerhet",processOwner:"CISO",date:"2026-01-26",reviewed:true,priority:"medium",goals:["G-13"],parentId:"T-005",actualHours:6,assignee:"m5",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-26 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-06 15:00"}],attachments:[]},
  {id:"T-005-B",title:"Konfigurere Azure AD Enterprise Apps",desc:"Sette opp SSO for hvert system i Azure AD.",tracks:["sysdev"],size:5,status:"ready",sprintId:"S-28",submitterName:"Jonas Ribe",submitterDept:"Sikkerhet",processOwner:"CISO",date:"2026-01-26",reviewed:true,priority:"medium",goals:["G-13"],parentId:"T-005",assignee:"m5",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-26 08:00"}],attachments:[]},
  {id:"T-005-C",title:"Test og utrulling SSO",desc:"Pilottest og gradvis utrulling til alle avdelinger.",tracks:["sysdev"],size:3,status:"ready",sprintId:"S-29",submitterName:"Jonas Ribe",submitterDept:"Sikkerhet",processOwner:"CISO",date:"2026-01-26",reviewed:true,priority:"medium",goals:["G-13"],parentId:"T-005",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-01-26 08:00"}],attachments:[]},

  // ═══ T-006: Redesigne onboarding-flyt (Low code) — PÅGÅR ═══
  {id:"T-006",title:"Redesigne onboarding-flyt",desc:"Power Apps onboarding for nye ansatte med automatisk tilgangsstyring og sjekklister.",tracks:["lowcode"],size:0,status:"in-progress",sprintId:"S-28",submitterName:"Sofie Aasen",submitterDept:"HR",processOwner:"HR-leder",date:"2026-02-01",parentId:null,reviewed:true,priority:"medium",goals:["G-17","G-20"],
    enterprise:"hemit",solutionCategory:"lowcode",
    manualTask:"yes",taskPerformer:"HR-rådgivere",frequency:"Ukentlig",volumePerTime:"3-5 nyansatte",annualTimeSaving:"300",involvedSystems:"Power Apps, SharePoint, Azure AD, Visma",
    needSummary:"Digitalisere onboarding med automatisk opprettelse av kontoer og sjekklister",background:"HR bruker 4-6 timer per nyansatt på manuell onboarding med e-poster og Excel-sjekklister",
    regulatory:3,security:4,costSaving:6,dataQuality:5,simplicity:8,patientBenefit:0,employeeSat:8,
    regulatoryReason:"GDPR-krav om håndtering av personalopplysninger",securityReason:"Automatisk tilgangsstyring reduserer risiko",costSavingReason:"6 timer/nyansatt × 50/år = 300 t/år",dataQualityReason:"Strukturerte data erstatter e-post",simplicityReason:"Forenkler kompleks manuell prosess",patientBenefitReason:"Ingen direkte effekt",employeeSatReason:"Bedre førsteinntrykk for nyansatte",
    expectedBenefit:"Halvere tidsbruk per onboarding",benefitCategory:"time",benefitClassification:"kvantitativ",benefitUnit:"timer",benefitMetric:"Timer per onboarding",benefitBaseline:"6",benefitTarget:"2",benefitActual:"",benefitOwner:"Sofie Aasen",estimatedCost:"40000",estimatedAnnualSaving:"120000",personalData:"yes",
    comments:[{author:"HR-leder",text:"Piloterer med IT-avd. først.",time:"2026-02-05 09:00"}],
    history:[{who:"System",what:"Opprettet",time:"2026-02-01 08:00"},{who:"Utviklingsforum",what:"status → \"assessed\"",time:"2026-02-03 10:00"},{who:"System",what:"status → \"in-progress\"",time:"2026-02-17 09:00"}],attachments:[]},
  {id:"T-006-A",title:"Prototyping onboarding-app",desc:"Skisser og Power Apps prototype.",tracks:["lowcode"],size:2,status:"done",sprintId:"S-27",submitterName:"Sofie Aasen",submitterDept:"HR",processOwner:"HR-leder",date:"2026-02-02",reviewed:true,priority:"medium",goals:["G-17"],parentId:"T-006",actualHours:8,assignee:"m4",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-02 08:00"},{who:"System",what:"status → \"done\"",time:"2026-02-12 14:00"}],attachments:[]},
  {id:"T-006-B",title:"Konfigurasjon og bygging onboarding",desc:"Bygge Power App med flows og SharePoint-lister.",tracks:["lowcode"],size:5,status:"in-progress",sprintId:"S-28",submitterName:"Sofie Aasen",submitterDept:"HR",processOwner:"HR-leder",date:"2026-02-02",reviewed:true,priority:"medium",goals:["G-17"],parentId:"T-006",actualHours:10,assignee:"m4",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-02 08:00"},{who:"System",what:"status → \"in-progress\"",time:"2026-02-17 10:00"}],attachments:[]},
  {id:"T-006-C",title:"Brukertesting onboarding",desc:"Teste med HR og 5 nyansatte som pilot.",tracks:["lowcode"],size:2,status:"ready",sprintId:"S-29",submitterName:"Sofie Aasen",submitterDept:"HR",processOwner:"HR-leder",date:"2026-02-02",reviewed:true,priority:"medium",goals:["G-17"],parentId:"T-006",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-02 08:00"}],attachments:[]},

  // ═══ T-007: Lisenshåndteringsverktøy (COTS) — VURDERT ═══
  {id:"T-007",title:"Lisenshåndteringsverktøy",desc:"Erstatte Excel med hyllevare for lisensforvaltning og kostnadsoptimalisering.",tracks:["cots"],size:0,status:"assessed",sprintId:null,submitterName:"Ida Berg",submitterDept:"Innkjøp",processOwner:"IT innkjøpsansvarlig",date:"2026-02-03",parentId:null,reviewed:true,priority:"medium",goals:["G-22"],
    enterprise:"hemit",solutionCategory:"unknown",
    manualTask:"yes",taskPerformer:"IT-innkjøp",frequency:"Månedlig",volumePerTime:"200+ lisenser",annualTimeSaving:"150",involvedSystems:"Excel, ServiceNow, Azure AD",
    needSummary:"Sentralisert lisenshåndtering med automatisk varsling ved fornyelse",background:"Lisensdata er spredt i flere Excel-filer, oversikt mangler og vi har betalt for ubrukte lisenser",
    regulatory:2,security:3,costSaving:8,dataQuality:7,simplicity:6,patientBenefit:0,employeeSat:4,
    regulatoryReason:"Lisensrevisjoner krever sporbarhet",securityReason:"Sikrer at kun autoriserte lisenser er i bruk",costSavingReason:"Avdekket 400k i ubrukte lisenser siste år",dataQualityReason:"Sentralisert og oppdatert lisensoversikt",simplicityReason:"Erstatter mange Excel-filer med ett system",patientBenefitReason:"Ingen effekt",employeeSatReason:"Marginal forbedring for IT-innkjøp",
    expectedBenefit:"Redusere lisenskostnader med 15%",benefitCategory:"cost",benefitClassification:"kvantitativ",benefitUnit:"kr",benefitMetric:"Årlige lisenskostnader",benefitBaseline:"3200000",benefitTarget:"2720000",benefitActual:"",benefitOwner:"Ida Berg",estimatedCost:"120000",estimatedAnnualSaving:"480000",
    comments:[{author:"Utviklingsforum",text:"Vurderer Flexera vs Snow Software.",time:"2026-02-05 14:00"}],
    history:[{who:"System",what:"Opprettet",time:"2026-02-03 08:00"},{who:"Utviklingsforum",what:"status → \"assessed\"",time:"2026-02-05 14:00"}],attachments:[]},

  // ═══ T-008: Migrere legacy-API (Integrasjon + Sysdev) — BLOKKERT ═══
  {id:"T-008",title:"Migrere legacy-API",desc:"Flytte 12 SOAP-tjenester til REST – blokkerer flere initiativ.",tracks:["integration","sysdev"],size:21,status:"blocked",sprintId:null,submitterName:"Lise Berg",submitterDept:"Arkitektur",processOwner:"Sjefsarkitekt",date:"2026-01-15",parentId:null,reviewed:true,priority:"high",goals:["G-01","G-13"],
    enterprise:"hmn",solutionCategory:"integration",
    manualTask:"no",involvedSystems:"EPJ, Lab, Røntgen, Matrise",
    needSummary:"Migrere alle SOAP-baserte integrasjoner til REST",background:"12 aldrende SOAP-tjenester forårsaker ustabilitet og blokkerer modernisering",
    regulatory:4,security:6,costSaving:6,dataQuality:5,simplicity:7,patientBenefit:4,employeeSat:5,
    regulatoryReason:"Gamle API-er oppfyller ikke nye sikkerhetskrav",securityReason:"REST med OAuth2 er sikrere enn SOAP med sertifikater",costSavingReason:"Redusert vedlikeholdskostnad for integrasjoner",dataQualityReason:"Bedre datakonsistens med ny API-standard",simplicityReason:"Standardisert API-design forenkler utvikling",patientBenefitReason:"Mer stabile kliniske systemer",employeeSatReason:"Enklere for utviklere å vedlikeholde",
    estimatedCost:"500000",estimatedAnnualSaving:"300000",
    blockedBy:[],
    comments:[{author:"Utviklingsforum",text:"Blokkert av leverandør – venter på ny versjon av EPJ-API.",time:"2026-02-01 14:00"}],
    history:[{who:"System",what:"Opprettet",time:"2026-01-15 08:00"},{who:"Utviklingsforum",what:"status → \"blocked\"",time:"2026-02-01 14:00"}],attachments:[]},

  // ═══ T-009: RPA for laboratorierekvisisjoner — VURDERT ═══
  {id:"T-009",title:"Automatisere laboratorierekvisisjoner",desc:"RPA-bot som henter rekvisisjonsdata fra papirskjema og registrerer i LIMS.",tracks:["rpa"],size:0,status:"assessed",sprintId:null,submitterName:"Marit Dahl",submitterDept:"Laboratoriemedisin",processOwner:"Lab-leder",date:"2026-02-05",parentId:null,reviewed:true,priority:"medium",goals:["G-03","G-11"],
    enterprise:"stolav",solutionCategory:"rpa",pilotUnit:"Medisinsk biokjemi",personalData:"yes",
    manualTask:"yes",taskPerformer:"Bioingeniører",frequency:"Daglig",volumePerTime:"150 rekvisisjoner",annualTimeSaving:"900",involvedSystems:"LIMS, Helseplattformen, ScanDoc",
    needSummary:"Automatisere registrering av papirbaserte laboratorierekvisisjoner",background:"30% av lab-rekvisisjoner kommer fortsatt på papir og registreres manuelt",
    regulatory:7,security:6,costSaving:7,dataQuality:9,simplicity:7,patientBenefit:6,employeeSat:8,
    regulatoryReason:"Lab-analyser er underlagt strenge kvalitetskrav",securityReason:"Behandler pasientdata fra rekvisisjoner",costSavingReason:"900 timer/år i manuell registrering",dataQualityReason:"Eliminerer registreringsfeil som kan påvirke prøvesvar",simplicityReason:"Automatiserer tidkrevende manuell prosess",patientBenefitReason:"Raskere og riktigere prøvesvar",employeeSatReason:"Bioingeniører kan fokusere på analyse",
    expectedBenefit:"Redusere manuell registrering av rekvisisjoner med 90%",benefitCategory:"time",benefitClassification:"kvantitativ",benefitUnit:"timer",benefitMetric:"Timer manuell registrering per dag",benefitBaseline:"4",benefitTarget:"0.5",benefitActual:"",benefitOwner:"Marit Dahl",estimatedCost:"100000",estimatedAnnualSaving:"180000",
    comments:[{author:"Utviklingsforum",text:"God kandidat for RPA – høy gevinst.",time:"2026-02-07 10:00"}],
    history:[{who:"System",what:"Opprettet",time:"2026-02-05 08:00"},{who:"Utviklingsforum",what:"status → \"assessed\"",time:"2026-02-07 10:00"}],attachments:[]},

  // ═══ T-010: E-signeringsløsning — INNMELDT ═══
  {id:"T-010",title:"E-signeringsløsning",desc:"Digital signering for kontrakter, samtykker og kliniske dokumenter.",tracks:[],size:0,status:"submitted",sprintId:null,submitterName:"Toril Strand",submitterDept:"Jus",processOwner:"Juridisk rådgiver",date:"2026-02-12",parentId:null,reviewed:false,priority:"high",goals:["G-04"],
    enterprise:"hmn",solutionCategory:"unknown",personalData:"yes",
    manualTask:"yes",taskPerformer:"Juridisk avd. og klinikere",frequency:"Daglig",volumePerTime:"20 dokumenter",annualTimeSaving:"500",involvedSystems:"SharePoint, Public 360, Helseplattformen",
    needSummary:"Innføre digital signering for alle typer dokumenter i helseforetakene",background:"Fysisk signering er tidkrevende, forsinker avtaler og skaper papirarkiv",
    qualitativeBenefits:"Raskere saksbehandling, sporbarhet, fjernarbeid",quantitativeBenefits:"500 timer/år, redusert papirkostnad",
    comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-12 08:00"}],attachments:[]},

  // ═══ T-011: Digital operasjonsplanlegging — INNMELDT ═══
  {id:"T-011",title:"Digital operasjonsplanlegging",desc:"Erstatte whiteboard med digital planlegging av operasjonsprogrammet.",tracks:[],size:0,status:"submitted",sprintId:null,submitterName:"Dr. Knut Aasen",submitterDept:"Kirurgi",processOwner:"Avd.sjef kirurgi",date:"2026-02-14",parentId:null,reviewed:false,priority:"high",goals:["G-01","G-03"],
    enterprise:"stolav",solutionCategory:"sysdev",personalData:"yes",
    manualTask:"yes",taskPerformer:"Operasjonskoordinatorer",frequency:"Daglig",volumePerTime:"15-20 operasjoner",annualTimeSaving:"600",involvedSystems:"DIPS, Helseplattformen, Orbit",
    needSummary:"Digital planlegging og koordinering av operasjonsprogrammet",background:"Operasjonsprogrammet styres via whiteboard og telefon, endringer er vanskelig å kommunisere",
    qualitativeBenefits:"Bedre koordinering, færre avlysninger, sanntidsoversikt",quantitativeBenefits:"600 timer/år spart, 20% færre avlysninger pga. bedre planlegging",
    comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-14 08:00"}],attachments:[]},

  // ═══ T-012: Automatisk prøvesvar-varsling — INNMELDT ═══
  {id:"T-012",title:"Automatisk prøvesvar-varsling",desc:"Push-varsling til behandlende lege når kritiske prøvesvar foreligger.",tracks:[],size:0,status:"submitted",sprintId:null,submitterName:"Dr. Line Haug",submitterDept:"Medisinsk avd.",processOwner:"Overlege medisin",date:"2026-02-18",parentId:null,reviewed:false,priority:"medium",goals:["G-11","G-03"],
    enterprise:"hnt",solutionCategory:"integration",personalData:"yes",
    manualTask:"yes",taskPerformer:"Lab-personell og sykepleiere",frequency:"Daglig",volumePerTime:"30-50 kritiske svar",annualTimeSaving:"400",involvedSystems:"LIMS, Helseplattformen, Mobilapp",
    needSummary:"Automatisk push-varsling ved kritiske prøvesvar",background:"Kritiske prøvesvar varsles manuelt per telefon, noe som forsinker behandling",
    qualitativeBenefits:"Raskere respons på kritiske svar, bedre pasientsikkerhet",quantitativeBenefits:"400 timer/år spart, gjennomsnittlig responstid ned fra 45 til 5 minutter",
    comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-18 08:00"}],attachments:[]},

  // ═══ T-013: Reiseregningsbot (RPA) — INNMELDT ═══
  {id:"T-013",title:"Automatisere reiseregninger",desc:"RPA-bot for automatisk utfylling og kontroll av reiseregninger i SAP.",tracks:[],size:0,status:"submitted",sprintId:null,submitterName:"Anders Moe",submitterDept:"Økonomiavd.",processOwner:"Regnskapssjef",date:"2026-02-19",parentId:null,reviewed:false,priority:"low",goals:["G-03","G-04"],
    enterprise:"hemit",solutionCategory:"rpa",personalData:"no",
    manualTask:"yes",taskPerformer:"Regnskapskonsulenter",frequency:"Ukentlig",volumePerTime:"60 reiseregninger",annualTimeSaving:"350",involvedSystems:"SAP, Concur, Outlook",
    needSummary:"Automatisere kontroll og bokføring av reiseregninger",background:"Manuell kontroll av reiseregninger tar 15 min/stk, ofte feil som krever retur til ansatt",
    qualitativeBenefits:"Redusert feilrate, raskere utbetaling",quantitativeBenefits:"350 timer/år, 80% reduksjon i returer pga feil",
    comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-19 08:00"}],attachments:[]},

  // ═══ T-014: Avviksmeldingsapp (Low code) — KLAR ═══
  {id:"T-014",title:"Digital avviksmelding",desc:"Power App for enkel rapportering av avvik med automatisk varsling til rett mottaker.",tracks:["lowcode"],size:0,status:"ready",sprintId:"S-29",submitterName:"Ona Nilsen",submitterDept:"Kvalitet",processOwner:"Kvalitetssjef",date:"2026-02-07",parentId:null,reviewed:true,priority:"medium",goals:["G-04","G-12"],
    enterprise:"hemit",solutionCategory:"lowcode",personalData:"unknown",
    manualTask:"yes",taskPerformer:"Alle ansatte",frequency:"Daglig",volumePerTime:"5-10 avvik",annualTimeSaving:"200",involvedSystems:"Power Apps, SharePoint, Teams, EQS",
    needSummary:"Erstatte papirskjema for avviksrapportering med mobilapp",background:"Papirbaserte avviksskjemaer gir forsinket rapportering og vanskelig oppfølging",
    regulatory:6,security:3,costSaving:4,dataQuality:7,simplicity:9,patientBenefit:5,employeeSat:7,
    regulatoryReason:"Lovpålagt avvikshåndtering",securityReason:"Lav risiko – avvik er ikke persondata",costSavingReason:"Moderat – 200 t/år",dataQualityReason:"Strukturerte avviksdata med kategorisering",simplicityReason:"Svært enkel å bruke – erstatter papirskjema med mobilapp",patientBenefitReason:"Raskere avvikshåndtering kan forbedre pasientsikkerhet",employeeSatReason:"Enklere å melde avvik",
    expectedBenefit:"Doble antall rapporterte avvik gjennom enklere melding",benefitCategory:"quality",benefitClassification:"kvantitativ",benefitUnit:"antall",benefitMetric:"Avviksmeldinger per måned",benefitBaseline:"40",benefitTarget:"80",benefitActual:"",benefitOwner:"Ona Nilsen",estimatedCost:"25000",estimatedAnnualSaving:"60000",
    comments:[{author:"Utviklingsforum",text:"Lav kostnad, god effekt. Prioritert til S-29.",time:"2026-02-10 11:00"}],
    history:[{who:"System",what:"Opprettet",time:"2026-02-07 08:00"},{who:"Utviklingsforum",what:"status → \"assessed\"",time:"2026-02-10 11:00"},{who:"System",what:"status → \"ready\"",time:"2026-02-15 09:00"}],attachments:[]},
  {id:"T-014-A",title:"Prototyping avviksapp",desc:"Skisser og Power Apps prototype.",tracks:["lowcode"],size:2,status:"ready",sprintId:"S-29",submitterName:"Ona Nilsen",submitterDept:"Kvalitet",processOwner:"Kvalitetssjef",date:"2026-02-16",reviewed:true,priority:"medium",goals:["G-04"],parentId:"T-014",assignee:"m4",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-16 08:00"}],attachments:[]},
  {id:"T-014-B",title:"Konfigurasjon avviksskjema og flows",desc:"Bygge Power App med Power Automate varsling.",tracks:["lowcode"],size:5,status:"ready",sprintId:"S-29",submitterName:"Ona Nilsen",submitterDept:"Kvalitet",processOwner:"Kvalitetssjef",date:"2026-02-16",reviewed:true,priority:"medium",goals:["G-04"],parentId:"T-014",assignee:"m4",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-16 08:00"}],attachments:[]},
  {id:"T-014-C",title:"Brukertesting avviksapp",desc:"Teste med 3 avdelinger som piloter.",tracks:["lowcode"],size:2,status:"ready",sprintId:"S-30",submitterName:"Ona Nilsen",submitterDept:"Kvalitet",processOwner:"Kvalitetssjef",date:"2026-02-16",reviewed:true,priority:"medium",goals:["G-04"],parentId:"T-014",comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-16 08:00"}],attachments:[]},

  // ═══ T-015: Digital PROM-innsamling i YOUwell — INNMELDT ═══
  {id:"T-015",title:"Digital PROM-innsamling i YOUwell",desc:"Opprette digitale PROM-skjemaer i YOUwell for systematisk innsamling av pasientrapporterte data for ortopedisk avdeling.",tracks:[],size:0,status:"submitted",sprintId:null,submitterName:"Dr. Maria Lund",submitterDept:"Ortopedisk avd.",processOwner:"Avdelingssjef ortopedi",date:"2026-02-20",parentId:null,reviewed:false,priority:"high",goals:["G-02","G-03"],
    enterprise:"stolav",solutionCategory:"sysdev",personalData:"yes",
    manualTask:"yes",taskPerformer:"Sykepleiere og fysioterapeuter",frequency:"Daglig",volumePerTime:"25 pasienter",annualTimeSaving:"450",involvedSystems:"YOUwell, Helseplattformen, HelseNorge",
    needSummary:"Digitalisere innsamling av pasientrapporterte utkomstmål (PROM) via YOUwell-plattformen",background:"PROM-data samles inn på papir og registreres manuelt, noe som gir lav svarprosent og forsinkede data",
    qualitativeBenefits:"Bedre datakvalitet, høyere svarprosent, systematisk oppfølging av behandlingsresultater",quantitativeBenefits:"450 timer/år spart, svarprosent forventet økt fra 40% til 80%",
    regulatory:7,security:6,costSaving:5,dataQuality:9,simplicity:7,patientBenefit:8,employeeSat:6,
    regulatoryReason:"Nasjonale kvalitetsregistre krever systematisk PROM-innsamling for ortopediske inngrep",securityReason:"Behandler sensitiv helseinformasjon via digital plattform – krever sikker autentisering",costSavingReason:"450 timer/år i manuell registrering og purring på papirskjemaer",dataQualityReason:"Strukturert digital innsamling eliminerer manuelle registreringsfeil og gir sanntidsdata",simplicityReason:"Pasienter fyller ut skjema digitalt hjemmefra eller på nettbrett ved oppmøte",patientBenefitReason:"Systematisk PROM gir bedre oppfølging og tilpasset behandling basert på pasientens egne rapporteringer",employeeSatReason:"Fjerner manuell registrering og purring på papirskjemaer for sykepleiere",
    comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-20 08:00"}],attachments:[]},

  // ═══ T-016: Digital screening psykisk helse i Checkware — INNMELDT ═══
  {id:"T-016",title:"Digital screening psykisk helse i Checkware",desc:"Opprette og konfigurere standardiserte screeningskjemaer (PHQ-9, GAD-7) i Checkware for psykiatrisk poliklinikk.",tracks:[],size:0,status:"submitted",sprintId:null,submitterName:"Dr. Kristin Myhre",submitterDept:"Psykiatrisk poliklinikk",processOwner:"Avdelingssjef psykiatri",date:"2026-02-20",parentId:null,reviewed:false,priority:"medium",goals:["G-02","G-04"],
    enterprise:"hnt",solutionCategory:"sysdev",personalData:"yes",
    manualTask:"yes",taskPerformer:"Psykologer og psykiatere",frequency:"Daglig",volumePerTime:"30 konsultasjoner",annualTimeSaving:"350",involvedSystems:"Checkware, Helseplattformen, DIPS",
    needSummary:"Digitalisere psykisk helse-screening med validerte skjemaer (PHQ-9, GAD-7) i Checkware",background:"Screeningskjemaer fylles ut på papir ved oppmøte, scores manuelt og resultater registreres i journal for hånd",
    qualitativeBenefits:"Standardisert scoring, automatisk trendanalyse, bedre behandlingsplanlegging",quantitativeBenefits:"350 timer/år spart på manuell scoring og registrering",
    regulatory:6,security:7,costSaving:5,dataQuality:8,simplicity:8,patientBenefit:7,employeeSat:7,
    regulatoryReason:"Nasjonale retningslinjer anbefaler systematisk screening med validerte verktøy for psykisk helse",securityReason:"Sensitiv psykisk helseinformasjon krever sikker håndtering og tilgangsstyring",costSavingReason:"350 timer/år i manuell scoring, registrering og arkivering av papirskjemaer",dataQualityReason:"Automatisk scoring eliminerer beregningsfeil og gir strukturerte data for forskning og kvalitetsforbedring",simplicityReason:"Pasienter fyller ut på nettbrett før konsultasjon, automatisk scoring tilgjengelig umiddelbart",patientBenefitReason:"Raskere og mer presis vurdering av symptombelastning, bedre oppfølging over tid med trendgrafer",employeeSatReason:"Slipper manuell scoring og dobbeltregistrering – mer tid til pasientkontakt",
    comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-20 09:00"}],attachments:[]},

  // ═══ T-017: Automatisert vaktplanlegging — INNMELDT ═══
  {id:"T-017",title:"Automatisert vaktplanlegging",desc:"Erstatte manuell vaktplanlegging i Excel med automatisert løsning som tar hensyn til kompetansekrav, arbeidstidsbestemmelser og ønsker.",tracks:[],size:0,status:"submitted",sprintId:null,submitterName:"Bente Kvam",submitterDept:"HR",processOwner:"HR-sjef",date:"2026-02-21",parentId:null,reviewed:false,priority:"medium",goals:["G-17","G-04"],
    enterprise:"stolav",solutionCategory:"unknown",personalData:"yes",
    manualTask:"yes",taskPerformer:"Avdelingsledere og HR-rådgivere",frequency:"Ukentlig",volumePerTime:"12 avdelingsplaner",annualTimeSaving:"700",involvedSystems:"GAT, Visma, Excel",
    needSummary:"Automatisere vaktplanlegging med hensyn til arbeidstidsregler og kompetansekrav",background:"Avdelingsledere bruker 8-10 timer/uke på manuell vaktplanlegging i Excel, ofte med brudd på AML",
    qualitativeBenefits:"Bedre overholdelse av arbeidstidsbestemmelser, mer rettferdig fordeling, redusert stress for ledere",quantitativeBenefits:"700 timer/år spart, 90% reduksjon i AML-brudd",
    regulatory:8,security:4,costSaving:7,dataQuality:6,simplicity:8,patientBenefit:3,employeeSat:9,
    regulatoryReason:"Arbeidsmiljølovens krav om forsvarlig arbeidstid, hvileperioder og maksimal overtid",securityReason:"Personaldata behandles, men begrenset risiko sammenlignet med pasientdata",costSavingReason:"700 timer/år frigjort for avdelingsledere som i dag bruker på manuell planlegging",dataQualityReason:"Automatisk validering mot AML-regler gir korrekte vaktplaner uten manuelle feil",simplicityReason:"Erstatter kompleks manuell prosess med automatisert forslag som tar hensyn til alle regler",patientBenefitReason:"Indirekte – bedre bemanningsplanlegging sikrer riktig kompetanse på vakt",employeeSatReason:"Mer forutsigbar arbeidstid, rettferdig fordeling av ubeleilige vakter, redusert belastning for ledere",
    comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-21 08:00"}],attachments:[]},

  // ═══ T-018: Digital smittesporingsløsning — INNMELDT ═══
  {id:"T-018",title:"Digital smittesporingsløsning",desc:"Utvikle digital løsning for smittesporing og utbruddshåndtering med automatisk varsling og kontaktsporing.",tracks:[],size:0,status:"submitted",sprintId:null,submitterName:"Dr. Ola Strand",submitterDept:"Smittevern",processOwner:"Smittevernoverlege",date:"2026-02-21",parentId:null,reviewed:false,priority:"high",goals:["G-11","G-15"],
    enterprise:"hmn",solutionCategory:"sysdev",personalData:"yes",
    manualTask:"yes",taskPerformer:"Smittevernsykepleiere",frequency:"Daglig",volumePerTime:"10-15 hendelser",annualTimeSaving:"500",involvedSystems:"MSIS, Helseplattformen, FHI Rapportering",
    needSummary:"Digitalisere smittesporing med automatisk kontaktidentifisering og varsling ved utbrudd",background:"Smittesporing gjøres manuelt med telefon og regneark, noe som forsinker respons ved utbrudd betydelig",
    qualitativeBenefits:"Raskere responstid ved utbrudd, bedre oversikt, standardisert håndtering på tvers av HF",quantitativeBenefits:"500 timer/år spart, responstid ned fra 24 timer til 2 timer ved utbrudd",
    regulatory:9,security:8,costSaving:5,dataQuality:8,simplicity:6,patientBenefit:7,employeeSat:6,
    regulatoryReason:"Smittevernloven pålegger meldeplikt og systematisk sporing – digitalisering sikrer etterlevelse",securityReason:"Behandler svært sensitiv helseinformasjon om smittsomme sykdommer og kontaktpersoner",costSavingReason:"500 timer/år i manuell sporing, telefonering og rapportering til FHI",dataQualityReason:"Strukturert digital registrering gir komplett sporingsdata med tidsstempler og koblingsinformasjon",simplicityReason:"Automatiserer kontaktidentifisering basert på pasientbevegelser og romlokasjon",patientBenefitReason:"Raskere smittesporing beskytter innlagte pasienter mot nosokomial smittespredning",employeeSatReason:"Reduserer stressende manuelt arbeid under utbruddssituasjoner",
    comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-21 09:00"}],attachments:[]},

  // ═══ T-019: Digital kompetanseoversikt og opplæringsportal — INNMELDT ═══
  {id:"T-019",title:"Digital kompetanseoversikt og opplæringsportal",desc:"Sentralisert løsning for kompetansekartlegging, obligatorisk opplæring og sertifiseringssporing.",tracks:[],size:0,status:"submitted",sprintId:null,submitterName:"Anette Dahl",submitterDept:"Fagutvikling",processOwner:"Fagsjef",date:"2026-02-21",parentId:null,reviewed:false,priority:"medium",goals:["G-17","G-18"],
    enterprise:"hemit",solutionCategory:"unknown",personalData:"yes",
    manualTask:"yes",taskPerformer:"Fagledere og HR",frequency:"Ukentlig",volumePerTime:"50 registreringer",annualTimeSaving:"400",involvedSystems:"LMS, SharePoint, Visma",
    needSummary:"Sentralisere kompetanseoversikt og automatisere påminnelser om obligatorisk opplæring",background:"Kompetansedata er spredt i flere systemer og Excel-filer, vanskelig å ha oversikt over sertifiseringer og pålagt opplæring",
    qualitativeBenefits:"Bedre oversikt over kompetanse, enklere å identifisere kompetansegap, automatisk varsling ved utløpte sertifiseringer",quantitativeBenefits:"400 timer/år spart på manuell oppfølging, 95% etterlevelse av obligatorisk opplæring",
    regulatory:6,security:3,costSaving:5,dataQuality:7,simplicity:7,patientBenefit:4,employeeSat:7,
    regulatoryReason:"Krav om dokumentert kompetanse for helsepersonell og gjennomført obligatorisk opplæring",securityReason:"Begrenset risiko – personaldata men ikke sensitiv helseinformasjon",costSavingReason:"400 timer/år i manuell oppfølging, purring og rapportering på kompetansekrav",dataQualityReason:"Sentralisert kompetanseregister erstatter fragmenterte Excel-filer og gir oppdatert oversikt",simplicityReason:"Én portal for alle opplæringsbehov og kompetansedokumentasjon – erstatter mange kilder",patientBenefitReason:"Sikrer at helsepersonell har pålagt kompetanse og oppdaterte sertifiseringer",employeeSatReason:"Enklere å finne relevante kurs, spore egen utvikling og dokumentere kompetanse",
    comments:[],history:[{who:"System",what:"Opprettet",time:"2026-02-21 10:00"}],attachments:[]},
];

export const INIT_CONFIG={defaultSprintWeeks:2,notifyEmails:["utviklingsforum@hemit.no","leder@hemit.no"],emailNotifications:true,emailOnStatusChange:true,emailOnReview:true,notifyProcessOwner:true,scoringWeights:{wsjf:60,trackSpecific:40},dpiaLink:"https://eqs.hemit.no/doc/DPIA-mal-2024",dpiaEqsRef:"EQS-2024-0200 DPIA-prosedyre",
  auth:{enabled:false,provider:"azure-ad",tenantId:"",clientId:"",allowedDomains:["hemit.no","helse-midt.no","helseplattformen.no"],requireMfa:false,sessionTimeout:480,
    roleMappings:[
      {id:"rm1",groupId:"",groupName:"IT Utviklingsforum",role:"forum"},
      {id:"rm2",groupId:"",groupName:"Leveranseteam",role:"team"},
      {id:"rm3",groupId:"",groupName:"IT Administrasjon",role:"admin"},
    ],
    defaultRole:"employee",autoProvision:true,
  },
  azureDevOps:{enabled:false,orgUrl:"",pat:"",defaultProject:"",syncWorkItems:true,syncOnStatusChange:true,
    fieldMapping:{title:"System.Title",description:"System.Description",priority:"Microsoft.VSTS.Common.Priority",status:"System.State"},
    workItemType:"User Story",areaPath:"",iterationPath:"",
    statusMapping:[
      {id:"sm1",appStatus:"ready",devOpsState:"New"},
      {id:"sm2",appStatus:"in-progress",devOpsState:"Active"},
      {id:"sm3",appStatus:"done",devOpsState:"Closed"},
    ],
  },
  serviceNow:{enabled:false,instanceUrl:"",authMethod:"basic",username:"",password:"",clientId:"",clientSecret:"",
    syncIncidents:true,syncChangeRequests:false,syncOnStatusChange:true,
    table:"incident",assignmentGroup:"",category:"Software",
    fieldMapping:{shortDescription:"title",description:"description",priority:"priority",state:"status"},
    statusMapping:[
      {id:"sn1",appStatus:"submitted",snowState:"New"},
      {id:"sn2",appStatus:"in-progress",snowState:"In Progress"},
      {id:"sn3",appStatus:"done",snowState:"Resolved"},
    ],
  },
  trackSubtasks:{
    rpa:[{title:"Kartlegge prosess (AS-IS)",size:3},{title:"Utvikle RPA-bot",size:5},{title:"Test og pilot",size:3}],
    integration:[{title:"Kartlegge integrasjonspunkter",size:3},{title:"Utvikle integrasjon",size:5},{title:"Test og verifisering",size:3}],
    sysdev:[{title:"Kravspesifikasjon",size:3},{title:"Design og arkitektur",size:3},{title:"Utvikling",size:8},{title:"Test og QA",size:3}],
    lowcode:[{title:"Prototyping",size:2},{title:"Konfigurasjon og bygging",size:5},{title:"Brukertesting",size:2}],
    cots:[{title:"Behovsanalyse",size:3},{title:"Leverandørvurdering",size:3},{title:"Implementering og tilpasning",size:5},{title:"Akseptansetest",size:3}],
  },
};

export const INIT_TEAM=[
  {id:"m1",name:"Lars Kristiansen",role:"Backend",availability:100,skills:["Backend","DevOps"],track:"sysdev"},
  {id:"m2",name:"Marte Solberg",role:"Frontend",availability:80,skills:["Frontend","UX"],track:"sysdev"},
  {id:"m3",name:"Erik Nordli",role:"Fullstack",availability:60,skills:["Frontend","Backend"],track:"integration"},
  {id:"m4",name:"Sofie Aasen",role:"UX/UI & Low code",availability:50,skills:["UX","Power Apps"],track:"lowcode"},
  {id:"m5",name:"Jonas Ribe",role:"QA & Sikkerhet",availability:100,skills:["QA","Sikkerhet"],track:"sysdev"},
  {id:"m6",name:"Ida Berg",role:"RPA-utvikler",availability:70,skills:["RPA","UiPath"],track:"rpa"},
  {id:"m7",name:"Kristin Hauge",role:"Integrasjonsutvikler",availability:80,skills:["Mulesoft","REST","FHIR"],track:"integration"},
];

export const INIT_SPRINTS=[
  {id:"S-21",name:"Sprint 21",start:"2025-09-15",end:"2025-09-26",weeks:2,status:"completed",planned:34,delivered:29},
  {id:"S-22",name:"Sprint 22",start:"2025-09-29",end:"2025-10-10",weeks:2,status:"completed",planned:38,delivered:35},
  {id:"S-23",name:"Sprint 23",start:"2025-10-13",end:"2025-10-24",weeks:2,status:"completed",planned:40,delivered:38},
  {id:"S-24",name:"Sprint 24",start:"2025-10-27",end:"2025-11-07",weeks:2,status:"completed",planned:36,delivered:36},
  {id:"S-25",name:"Sprint 25",start:"2025-11-10",end:"2025-11-21",weeks:2,status:"completed",planned:42,delivered:39},
  {id:"S-26",name:"Sprint 26",start:"2025-11-24",end:"2025-12-05",weeks:2,status:"completed",planned:38,delivered:37},
  {id:"S-27",name:"Sprint 27",start:"2026-02-03",end:"2026-02-14",weeks:2,status:"completed",planned:45,delivered:42},
  {id:"S-28",name:"Sprint 28",start:"2026-02-17",end:"2026-02-28",weeks:2,status:"active",planned:48,delivered:0},
  {id:"S-29",name:"Sprint 29",start:"2026-03-03",end:"2026-03-14",weeks:2,status:"planned",planned:0,delivered:0},
  {id:"S-30",name:"Sprint 30",start:"2026-03-17",end:"2026-03-28",weeks:2,status:"planned",planned:0,delivered:0},
];
